AuctionPlatform/AuctionPlatform/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings





urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',views.login_call),
    path('userdashboard/',views.userdashboard),
    path('signup/',views.signup),
    path('home/',views.home),
    path('seller/',include('seller.urls')),
    path('logout/',views.logout_call),
    path('bidder/',include('bidder.urls')),
    path('admin_user/',views.admin_user),
    path('add_category/',views.add_category),
    path('categories_list/',views.categories_list),
   
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AuctionPlatform/bidder/urls.py
from django.urls import path

from . import views


app_name="bidder"

urlpatterns=[

path('viewproduct/<int:id>',views.viewproduct,name="view_product"),

path('buy_product/',views.buy_product),

path('userprofile/',views.userprofile),

# path('bid_product/<int:id>',views.bid_product,name="bid_product"),

path('bid_update/<int:id>',views.bid_update,name="bid_update"),

path('bid_approve/<int:id>',views.bid_approve,name="bid_approve"),

path('win_proceed/<int:id>',views.win_proceed,name="win_proceed"),

path('category_edit/<int:id>',views.category_edit,name='category_edit'),

path('category_delete/<int:id>',views.category_delete,name='category_delete'),

path('auction_list/',views.auction_list),

path('admin_delete_product/<int:id>',views.admin_delete_product,name="admin_delete_product"),

path('add_new_user/',views.add_new_user),

path('user_list/',views.user_list),

path('user_delete/<int:id>',views.user_delete,name="user_delete"),

path('admin_update_detail/',views.admin_update_detail),

path('log_out/',views.log_out),
]

AuctionPlatform/templates/add_category.html
{% extends 'admin.html' %}
{%load staticfiles %}

 {% block 'content' %}

{% if messages %}

{% for i in messages %}

<div class="alert alert-success alert-dismissible fade show" role="alert">
  <strong>Success!</strong>{{i}}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

{% endfor %}

{% endif %}

{%  block 'record' %}

 <h6 class="border rounded p-2 table-primary">Add New Record</h6>

{% endblock %} 

 <div class="p-0 border"> 

 <form method="post">{% csrf_token %}
 					
	<div class="form-group rounded border p-2 m-3" style="background-color: #f2f2f2;">
		<label class="mb-1 ">Category Name</label>
		<input type="text" class="form-control" name="add_cat">
	</div>
	<div class="form-group mt-3 border rounded p-2 m-3" style="text-align: right;">
		{% block 'update'%}
		<input type="submit" class="btn btn-primary btn-sm" value="Submit">
		{% endblock %}
		<input type="reset" class="btn btn-secondary btn-sm" value="Reset">
		
	</div>
</form>
 	
 </div>


                        
{% endblock%}

AuctionPlatform/templates/admin_update_detail.html
{% extends 'add_category.html' %}



 {% block 'content' %}

{% if messages %}

{% for i in messages %}

<div class="alert alert-success alert-dismissible fade show" role="alert">
  <strong>Success!</strong>{{i}}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

{% endfor %}

{% endif %}

{%  block 'record' %}

 <h6 class="border rounded p-2 table-primary">UPDATE ADMIN</h6>

{% endblock %} 

 <div class="p-0 border rounded"> 

 <form method="post">{% csrf_token %}
 					
	<div class="form-group rounded border p-2 m-3" style="background-color: #f2f2f2;">
		<label class="mb-1 ">USERNAME</label>
		<input type="text" class="form-control" name="un" required=""  >
	</div>
	<div class="form-group rounded border p-2 m-3" style="background-color: #f2f2f2;">
		<label class="mb-1 ">PASSWORD</label>
		<input type="password" class="form-control" name="up" required="" >
	</div>
	<div class="form-group mt-3 border rounded p-2 m-3" style="text-align: right;">
		{% block 'update'%}
		<input type="submit" class="btn btn-primary btn-sm" value="Update">
		{% endblock %}
		<input type="reset" class="btn btn-secondary btn-sm" value="Reset">
		
	</div>
</form>
 	
 </div>


                        
{% endblock%}

 {% block 'log' %}
                              <a class="nav-link" href="/logout/">
                                <div class="sb-nav-link-icon"><i class="fas fa-sign-out-alt"></i></div>
                                Logout
                            </a>
   {% endblock %}

AuctionPlatform/templates/bid_product.html
{% extends 'viewproduct.html' %}
{% load staticfiles %}


  {% block 'bid_success_msg' %}

                {% if messages%}
                <div class="alert alert-success alert-dismissible fade show mt-5 remove_msg" role="alert">
                
                    {% for i in  messages %}

                    <strong>Success! </strong>{{i}} 

                    {% endfor %}
                
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            {% endif %}

{% endblock %}


 {%block 'update_bid' %}
            		{% if messages%}
					
 				
 					{% for i in  messages %}

 				<!-- 	<script>
 						var obj=document.getElementsByClassName("own_product")

 						// for (i in obj){

 						// 	obj[i].style.display="none"

 						// }
 						
 					</script> -->

 						<h6 class="text-success pl-lg-4 py-lg-3 pr-lg-5  remove_msg" style="text-align:center;font-weight:bold;">You have placed bid successfully with price.(Rs.{{bidding_amount}}) </h6>	

 					{% endfor %}

 					{%endif%}
                    
{% endblock %}  

{%block 'update_btn'%}


        				<button type="button" class="btn btn-dark text-light " style="font-size:18px;font-weight: bold;display:inline-block;  " onclick="Bidform('bid_form')">Update Price Now &nbsp;<span class="text-warning" >> </span></button>

{% endblock %}  

 {% block 'update_form'%}
            			<form method="post"  action="{% url 'bidder:bid_update' id=pobj.id%}">
                           

                            {% csrf_token %}

            				<div class="form-group mb-1">
            					<small style="display:block;text-align:center; ">Add your price(Rs) and submit .</small>
            					<input type="number" class="form-control" name="bid_amount">
            				</div>

            				<div class="form-group" style="text-align:center;">
            					<input type="submit" value="Submit" class="btn btn-primary text-light">
            					<input type="reset" value="Reset" class="btn btn-primary text-light">
            				</div>
            				
            			</form>
 {% endblock %}

   {%  block 'remove_msg' %}
        			<script type="text/javascript">


        				
            			function Bidform(id){
            				ob=document.getElementById(id)
            				ob.style.display="block"
            				removeobj=document.getElementsByClassName("remove_msg")

            				for(i in removeobj){
            					removeobj[i].style.display="none"
            				}
            			}
        			</script>
   {% endblock%}

AuctionPlatform/templates/categories_list.html
{% extends 'admin.html' %}

 {% block 'content' %}


 {% if messages %}

{% for i in messages %}

<div class="alert alert-success alert-dismissible fade show" role="alert">
  <strong>Success !</strong>{{i}}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

{% endfor %}

{% endif %}


<div class="border rounded ">
 
 {% block 'table' %}
	
<h6 class=" m-0 px-3 py-2 table-primary" >CONTENT MANAGER</h6>

<table class="table mb-0" style='text-align:center '>
	<tr style="background-color:#f2f2f2;" class="table-sm">
		<th >#</th>
		<th>Name</th>
		<th>Options</th>
	</tr>

	{% for i in cobj %}

	<tr>
		<td >{{i.s_no}}</td>
		<td>{{i.catname}}</td>
		<td><a href="{% url 'bidder:category_edit' id=i.id %}" style="color:black;display:inline-block;" class='mr-5'><i class="fas fa-pencil-alt"></i></a><a href="{% url 'bidder:category_delete' id=i.id %}" style="color:black;"><i class="fas fa-trash-restore-alt"></i></a></td>
	</tr>

	{% endfor %}
</table>

{% endblock %}	

</div>
                     
 {% endblock%}
 

AuctionPlatform/templates/category_edit.html
{% extends 'add_category.html' %}
{%load staticfiles %}

{% block 'update'%}
		<input type="submit" class="btn btn-primary btn-sm" value="Update">
{% endblock %}

{%  block 'record' %}

 <h6 class="border rounded p-2">Edit Old Record</h6>

{% endblock %} 

AuctionPlatform/templates/checkout_form.html
{% extends 'sellproduct.html' %}
{% load staticfiles %}

{% block 'sell_product'%}


<div class="container ">
	

	<div class="row mt-md-5 mb-md-3">
		<div class="col-md-12"  ><span id="Product_auction_head">Checkout</span> <span id="Product_auction_head_1" >Now</span> </div>
		
	</div>
	<form method="post" >
		{% csrf_token %}
		<div class="row">
			<div class="col-md-4">
				<div class="form-group">
					<label>Product Name</label>
					<input type="text" name="p_name" value="{{bobj.product_name}}" readonly=""  class="form-control" style="background-color:#f2f2f2 ">
				</div>
			</div>
			<div class="col-md-4">
				<div class="form-group">
					<label>Product Price(Rs.)</label>
					<input type="number" name="p_price"  value="{{bobj.bid_amount}}" readonly=""   class="form-control"  style="background-color:#f2f2f2 ">
				</div>
				
			</div>
			<div class="col-md-4">
				<div class="form-group">
					<label>Select Payment Method</label>
					<select name="pyment_method" class="form-control">
						<option value="0" >select payment method</option>
						{% for i in  mobj%}
						<option value="{{i.method}}" >{{i.method}}</option>
						{% endfor %}
					</select>
				</div>
				
			</div>
		</div>
		<div class="row">

			<div class="col-md-12 ">
				<div class="form-group">
					<label>Shipping Address</label>
					<input type="text" name="shipping_address" value="{{bobj.shipping_address}}" class="form-control" style="height:80px;background-color:#f2f2f2; ">
				</div>	
			</div>
			
		</div>

		<div class="row mb-md-5 mt-md-4">

			<div class="col-md-12">
				<button class="btn btn-dark text-light btn-lg" type="submit">Submit</button>
				<button class="btn btn-dark text-light btn-lg" type="Reset">Reset</button>
			</div>
			
		</div>

	

	</form>

</div>


{% endblock %}

AuctionPlatform/templates/search.html
{% extends 'sellproduct.html' %}


{% block 'sell_product'%}
{% load staticfiles%}

<div class="container ">
	

	<div class="row mt-md-5 mb-md-5">
		<div class="col-md-12"  ><span id="Product_auction_head">Search</span> <span id="Product_auction_head_1" >Products</span> </div>
		{% if messages%}
			<div class="alert alert-success alert-dismissible fade show mt-5" role="alert">
 				
 				{% for i in  messages %}

 				<strong>Success!</strong>{{i}} 

 				{% endfor %}
 				
  					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    					<span aria-hidden="true">&times;</span>
  					</button>
			</div>
		{% endif %}
	</div>
	
<form  method="post" enctype="multipart/form-data">
		{% csrf_token%}
<div class="row mb-md-3">
	<div class="col-md-6">
		 <div class="form-group">
           
           <input style="background:#f2f2f2"  type="text" class="form-control" id="pn"  placeholder="Search" required="" name="p_name">
   
       </div>
	</div>
	
	<div class="col-md-6">

		<div class="form-group">
           				
           				<select id="uc" class="form-control" name="cat_id" required=""  >
           					<option value="0">Select Category</option>
           					{% for i in cobj%}
           						<option value="{{i.id}}">{{i.catname}}</option>

           					{% endfor%}
           				</select>           				
      	</div>
		
	</div>
</div>
	
	
	
	<div class="row mb-5">
		<div class="col-md-12">
			<button class="btn  text-light btn-lg p_sbtn" type="submit" style="background-color:black; ">Search</button>
			
		</div>
	</div>
</form>

<section class="py-2">
           <!--  <div class="container px-4 px-lg-5 mt-0"> -->
            	<!--  <div class="row mb-3">
    				<div class="col"><span style="font-size:40px;font-weight:bold;">Active</span><span style="font-size:40px;font-weight:200;"> Auctions</span>
    				</div>
    
				</div>  -->
              
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                  {% for i in pobj%}
                    <div class="col-lg-3 col mb-5">
                        <div class="card h-100 border-0">
                        	 <!-- Product Closing time-->
                            <div style="text-align:center;" class="p-3"><span class="p-1" style="font-weight:300;background-color:lightgray;font-size:20px;font-family:sans-serif;display: inline-block;   ">{{i.closing_date}}</span></div>
                            <!-- Product image-->
                            <img class="card-img-top" src="{{ i.cover_img.url }}" alt="Not Found" style="width:100%;height:200px;  " />
                            <!-- Product details-->
                            <div class="card-body pt-4 pl-4 pr-4 pb-0 mb-0">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h3  style="font-weight: bold;font-family:monospace; "><sup>Rs</sup>{{i.price}}</h3>
                                    <!-- Product price-->
                                   <span style="font-weight:400; "> {{i.name}} </span>
                                </div>
                            </div>
                            <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0  bg-transparent">
                <div class="text-center"><a class="btn btn-warning mt-auto" href="{% url 'bidder:view_product' id=i.id %}">Submit a bid</a></div>
                            </div>
                        </div>
                    </div>
                   {% endfor %}
                </div>
            <!-- </div> -->
</section>



</div>

{% endblock%}

AuctionPlatform/templates/user_list.html
{% extends 'categories_list.html' %}

{% block 'content' %}


 {% if messages %}

{% for i in messages %}

<div class="alert alert-success alert-dismissible fade show" role="alert">
  <strong>Success !</strong>{{i}}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

{% endfor %}

{% endif %}



 
 {% block 'table' %}
	
<h6 class=" m-0 px-3 py-2 border border-primary rounded table-primary" >CONTENT MANAGER</h6>

<table class="table mb-0 border rounded" style='text-align:center '>
	<tr style="background-color:#f2f2f2;" class="table-sm">
		<th >#</th>
		<th>First Name</th>
		<th>Last Name</th>
		<th>Username</th>
		

		<th>Option</th>
	</tr>

	{% for i in uobj %}

	<tr class="border">
		<td >{{i.s_no}}</td>
		<td>{{i.first_name}}</td>
		<td>{{i.last_name}}</td>
		<td>{{i.username}}</td>
		<td><a href="{% url 'bidder:user_delete' id=i.id %}" style="color:black;"><i class="fas fa-trash-restore-alt"></i></a></td>
	</tr>

	{% endfor %} 
</table>

{% endblock %}	

             
 {% endblock%}
 

AuctionPlatform/templates/userprofile.html
{% extends 'sellproduct.html' %}

{% load staticfiles %}

 {% block 'boot'%}

 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

 
 {% endblock %}

{% block 'sell_product'%}
{% load staticfiles%}

<div class="container ">
	

	<div class="row mt-md-5 mb-md-5">
		<div class="col-md-12"  ><span id="Product_auction_head">Update User</span> <span id="Product_auction_head_1" >Account</span> </div>
		{% if messages%}
			<div class="alert alert-success alert-dismissible fade show mt-5 " role="alert">
 				
 				{% for i in  messages %}

 				<strong>Success!</strong>{{i}} 

 				{% endfor %}
 				
  					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    					<span aria-hidden="true">&times;</span>
  					</button>
			</div>
		{% endif %}
	</div>
	
<form  method="post" enctype="multipart/form-data" >
		{% csrf_token%}
<div class="row mb-md-3">
	<div class="col-md-4">
		 <div class="form-group">
           <label for="fn">First Name</label>
           <input style="background: #f2f2f2 "  type="text" class="form-control" id="fn"  value="{{uobj.first_name}}" required="" name="first_name">
   
       </div>
	</div>
	<div class="col-md-4">

		<div class="form-group">
           			<label for="ln">Last Name</label>
           			<input style="background: #f2f2f2 "  value="{{uobj.last_name}}"  type="text" class="form-control" id="ln"  required="" name="last_name">
   
       	</div>
		
		
	</div>
	<div class="col-md-4">

		<div class="form-group">
           				<label for="un">Username</label>
           				<input style="background: #f2f2f2 " type="text" value="{{uobj.username}}"  class="form-control" id="un"  required="" name="user_name">
   
       </div>
		
	</div>
</div>
	<div class="row mb-md-3">
	<div class="col-md-4">
		
					<div class="form-group">
           				<label for="mn">Mobile Number</label>
           				<input style="background: #f2f2f2 " type="text" value="{{u_info_obj.mobile}}"  class="form-control" id="mn"  required="" name="mob">
   
       				</div>
	</div>
	<div class="col-md-4">

		<div class="form-group">
           				<label for="up">Password</label>
           				<input  style="background: #f2f2f2 " value="{{u_info_obj.password}}"   type="password" class="form-control" id="up"  required="" name="password">   
     	</div>
		
					
	</div>

	<div class="col-md-4">

		<div class="form-group">
           				<label for="ue">Email</label>
           				<input  style="background: #f2f2f2 " value="{{uobj.email}}"   type="email" class="form-control" id="ue"  required="" name="email">   
     	</div>
		
					
	</div>

	
	</div>
	<div class="row mb-md-3">
		<div class="col-md-12">
			<div class="form-group">
    		<label for="address">Address</label>
    		<input style="background:#f2f2f2;height:80px;  " class="form-control" id="address" value="{{u_info_obj.address}}"   name="address" placeholder="Address........">
  		</div>
		</div>
	</div>
	
	<div class="row mb-5">
		<div class="col-md-12">
			<button class="btn btn-dark text-light btn-lg p_sbtn" type="submit">Update Account</button>
			<button class="btn btn-dark text-light btn-lg p_sbtn" type="reset">Reset</button>
		</div>
	</div>
</form>

	<div class="row mt-md-5 mb-md-0">
		<div class="col-md-12"  ><span id="Product_auction_head">User Account </span> <span id="Product_auction_head_1" >Purchesh History</span> </div>
		
	</div>

	<div class="row mt-md-5 mb-md-5">

		<div class="col-md-12">

			<table class="table  table-bordered table-sm text-sec" style="text-align:center; ">
  				
   					 <tr style="background-color:#f2f2f2;font-weight: bold; " class="text-secondary">
      					<td >S.no</td>
      					<td>Name / Title</td>
					      <td>Bid Price(Rs)</td>
					      <td>Closing date</td>
					      <td>Status</td>
    				</tr>
  			
			 {% for i in pobj %}
			    <tr style="font-family: serif; ">
			      <td>{{i.s_no}}</td>
			      <td><a href="{% url 'bidder:view_product' id=i.id %}" class="b_product">{{i.name}}</a></td>
			      <td>{{i.bid_amt}}</td>
			      <td>{{i.closing_date}}</td>
			      <td><a href="{% url 'bidder:win_proceed' id=i.bid_id %}" class="win_product ">{{i.status}}</a></td>
			    </tr>
			{% endfor%}
			  
			</table>
			<script>
				var win_obj=document.getElementsByClassName("win_product")

				for(i in win_obj){
					if (win_obj[i].innerHTML=="Waiting"){

						win_obj[i].href="#"
						win_obj[i].style.color="black"
					}else if (win_obj[i].innerHTML=="Buy Successfully(Cash On Delivery)"){

						win_obj[i].href="#"
						win_obj[i].style.color="black"
					}
					else{
						win_obj[i].style.color="green"

					}
				}

			</script>
		</div>

	</div>

	<div class="row mt-md-5 mb-md-0">
		<div class="col-md-12"  ><span id="Product_auction_head">User Account </span> <span id="Product_auction_head_1" >Sale History</span> </div>
		
	</div>

	<div class="row mt-md-5 mb-md-5">

		<div class="col-md-12">

			<script>
				function Bidshow(class_name){
					var obj=document.getElementsByClassName(class_name);

					
					for (i in obj){

						obj[i].style.display="table-row";

					}


				}


			</script>


			{% for i in p_obj %}

			<table class="table   text-seconadry" >

  				
   					 <tr style="background-color:#f2f2f2; " class="text-secondary border-1">

   					 	<td colspan="5" ><div style="font-weight:500; ">{{i.Sno}}.&nbsp;&nbsp; {{i.name}} &nbsp;&nbsp; Rs. {{i.price}}&nbsp;&nbsp;  {{i.closing_date}}&nbsp;&nbsp; Number of bids({{i.num_of_bid}})   &nbsp;&nbsp;<span class="text-danger">{{i.product_status}}</span> <button onclick="Bidshow('{{i.Sno}}')" class="btn btn-sm btn-primary" style="font-weight:bold;float:right; ">view bid</button></div></td>
      					
    				</tr>

    				
    				 <tr style="font-weight:bold; text-align:center;display:none; "  class="text-secondary table-bordered table-sm {{i.Sno}}">
      					<td >S.no</td>
      					<td >User Name</td>
					      <td >Phone</td>

					     
					      <td>Bid Price(Rs)</td>
					      <td >Status</td>
    				</tr>

    				{% for k in i.product_bid %}

    				 <tr style=" text-align:center; font-family: serif;display:none; "  class="text-secondary table-bordered table-sm {{i.Sno}}">
      					<td >{{k.sn}}</td>
      					<td >{{k.fullname}}</td>
					      <td >{{k.mobile}}</td>

					     
					      <td>{{k.bid_amount}}</td>
					      <td><a  href="{% url 'bidder:bid_approve'  id=k.id %}" class="pro_approve">{{k.status}}</a></td>
    				</tr>

    					


    				{% endfor %}
  			
			
			</table>
			{% endfor %}

			<script type="text/javascript">

				var obj1=document.getElementsByClassName('pro_approve')

				for (i in obj1){


						if (obj1[i].innerHTML =="Sold Successfully"){
							
							obj1[i].style.color="black"

							obj1[i].href="#"
						}

					}
								
			</script>

		</div>

	</div>

</div>




{% endblock%}

 {% block 'nav'%}  
     <div class="bg-light py-lg-3 mb-3" style="box-shadow: 10px 10px 20px lightgray">   
        <nav class="navbar navbar-expand-lg navbar-light bg-light ">
            <div class="container px-4 px-lg-5 ">
                <a class="navbar-brand" href="#!"><img id="logo_img" src="{% static 'index/assets/auction6.png'%}" class="bg-warning" width="60px" height="60px"><span class="logo_content"> Online Auction Sytem</span></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse " id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto  mb-2 mb-lg-0 ">
                        <li class="nav-item "><a  class="nav-link n-link"  href="/userdashboard/">Home</a></li>
                         <li class="nav-item "><a  class="nav-link n-link"  href="#about">About</a></li>
                        <li class="nav-item "><a class="nav-link n-link" href="/seller/sellproduct/">Sell</a></li>
                        <li class="nav-item "><a class="nav-link n-link" href="/bidder/buy_product/">Buy</a></li>
                        <li class="nav-item "><a class="nav-link n-link" href="/seller/search/">Search</a></li>
                        <li class="nav-item"><a class="nav-link " href="#!">Contact Us</a></li>
                       
                    </ul>
                    
                </div>
            </div>
        </nav>
         </div>
        {% endblock%}